### ISSUE TITLE
x86 Big Sur - Login at Startup doesn't work

### ISSUE THREAD

**Issue by mankittens** [alin23/Lunar#218] opened 2020-12-01 04:38 UTC
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro 2017 13" nTB w/ Big Sur

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell S3230DGF

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    DisplayPort

- Using an USB Docking Station or Hub:
    CalDigit TS3+

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

# Issue description:
x86 MacBook with Big Sur installed. The Login at Startup setting is not working when enabled. Lunar does not start at startup.

**Comment by alin23** [comment] 2020-12-01 08:08
This issue has been tracked and fixed here: #25 
I'm not sure what the problem is but for some users this still doesn't work. It works for me on Big Sur and it has worked since the first developer beta in June so the OS version is not the problem.

I'll release the next version with an updated LaunchAtLogin framework, maybe that will fix it.

I'll close this as it has already been reported 3 times.

**Closed by alin23** 2020-12-01 08:08 UTC
