### ISSUE TITLE
Lunar Feature: More intuitive brightness key behaviors

### ISSUE THREAD

**Issue by Allen-Hu** [alin23/Lunar#313] opened 2021-04-30 13:42 UTC
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro 16-inch (2019)

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Acer VG272UP
    ViewSonic XG2405

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Thunderbolt 3 <-> Caldigit TS3 Dock <-> Both monitors

- Using an USB Docking Station or Hub:
    Yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync/Manual

# Issue description:

The following is what I observed:

1. "Use media keys as hotkeys" unchecked
Brightness keys change the brightness of the internal monitor, and it is then synced to all monitors, so indeed three monitors sync brightness, but the brightness indicator only shows on the internal monitor.

2. "Use media keys as hotkeys" checked
Brightness keys change the brightness of both external monitors when cursor is on the external monitor, and changes both external monitors by adjusting the "offset". It adjusts the brightness of the internal monitor when the cursor is on it.

It took me quite a while to realize what my keys are doing. I read that this is intended behavior from previous issues, and I think there is definitely some improvements that could be made. 

Using the current version, I would be only changing the external monitors' brightness if I use media keys as hotkeys, so I would just not use that function and let it change the internal monitors' brightness -> sync to all monitors. But then if I decided to switch to clamshell mode, Lunar would just switch to manual mode and my brightness keys would just become useless. 

This is what I think it should work like:

1. Media keys (brightness keys) should work the same as hotkeys in all circumstances.
2. When the internal monitor is on, brightness keys always change the brightness of the internal monitor.
3. Under manual mode, brightness keys change both external monitors' brightness.
4. Always show brightness indicators on all monitors/main monitor instead of internal/external/cursor monitor only.

I think the above behavior would be more intuitive compared to the current implementation.
Other than this, this program is really well designed and works extremely well, really appreciate it.

**Comment by alin23** [comment] 2021-04-30 14:02
Hi @Allen-Hu

Lunar 4 is in beta testing now and aims to solve this by adding an algorithm for learning from your manual changes.

Quote from the beta testing thread:
>### Self-adapting brightness curve (for users of adaptive modes: Sync, Location, Sensor)
>1. Whenever the brightness for a monitor isn’t quite right for you, adjust it manually using Lunar (both keyboard and UI controls work)
>2. Lunar should learn from that and adjust the algorithm curve so that it better matches your perception of light

So for example in Sync mode, the brightness keys (with the cursor on an external monitor) will adjust the actual brightness of that monitor (no more offsets to configure) and Lunar will map the current brightness of the built-in display to the new brightness of the external monitor. Same for contrast.

Lunar already supports hotkeys for adjusting brightness/contrast/volume on all monitors at once, you can find them on the Hotkeys page (_note that if your function keys work as media keys, you have to hold Fn to get an F2 key event instead of a Brightness Up event_):
<img width="591" alt="image" src="https://user-images.githubusercontent.com/3819725/116705502-4541cb00-a9d5-11eb-8ff9-2988bf4597ae.png">

The Media Keys feature will only change the brightness on the monitor you use so that you can fine tune each monitor when needed. Otherwise you would have to always use the UI which is not desirable for people that mostly use the keyboard (me included)

**Comment by Allen-Hu** [comment] 2021-04-30 14:26
@alin23 Thanks for the quick reply!
So I might be experiencing a bug then? My hotkeys only change the brightness on (both) external monitors, the internal monitor brightness remains the same when using hotkeys, at least in my case.

**Comment by alin23** [comment] 2021-04-30 14:29
Oh I see what you are saying now. Lunar doesn't change the built-in monitor brightness. It's only for external monitors.

If you use Sync mode, it's enough for you to change the built-in brightness normally (press the brightness keys with the cursor on the built-in monitor) and it will sync to other external monitors, having the same effect)
When you press the brightness keys on the built-in monitor, Lunar is bypassed and the macOS system handles this.

**Comment by Allen-Hu** [comment] 2021-04-30 14:43
Yes I get the idea. 

What I was trying to convey was that, say you always want to adjust brightness on all (including internal) monitors. When you use sync mode, you use brightness keys and it does the job all right. Now you want to switch to clamshell mode and you still want to adjust the brightness on all external monitors. You suddenly have to use hotkeys instead of the brightness keys.

I don't think it's really intuitive for having to use two different actions (brightness key/hotkey) to perform what is essentially the same task (changing brightness on all monitors). But I sure do understand that under the hood it is two different modes and work independently. 

Thus what I think should be the way is to make brightness keys control the internal monitor's brightness when it's on, then in clamshell mode, brightness keys automatically become equivalent to hotkeys, which change all external monitors' brightness.

**Comment by Allen-Hu** [comment] 2021-05-01 09:34
That would be great! Looking forward for it to be implemented.

**Comment by alin23** [comment] 2021-05-03 07:20
@Allen-Hu if you would like to beta test this feature, please send me a message at https://alinpanaitiu.com/contact/ so I can send you a beta build and a license code

**Comment by Allen-Hu** [comment] 2021-05-03 15:48
@alin23 Message sent!

**Comment by alin23** [comment] 2021-05-11 12:31
@vurtomatic Lunar doesn't control the built-in display. 

The beta simply changes how Lunar listens for the brightness keys so that:
* in Sync mode Lunar doesn't do anything and lets the system handle the brightness key (and then Lunar syncs the new brightness to the external monitors)
* in non-Sync modes Lunar changes the brightness of the display with the cursor on it (or leaves it to the system to do that if the cursor is on the built-in display)

Is this what you're expecting?

**Comment by vurtomatic** [comment] 2021-05-11 12:41
@alin23 I see, thank you for clarifying. Hmmm I'm trying to understand the use case.

So correct me if I'm wrong, the external display's brightness is controlled by Lunar, but built-in display is controlled by different keys on the laptop—which I guess is what this issue is about.

When using Lunar in this manner, won't the brightness level between the external display and built-display not match since they're adjusted individually?

I guess I thought one app—Lunar—will control and sync brightness level across external and built-in display.

I've downloaded the official release regardless, to see how this works. Thank you!

**Comment by alin23** [comment] 2021-05-11 13:17
> I guess I thought one app—Lunar—will control and sync brightness level across external and built-in display.

Indeed that's the purpose of Sync mode in Lunar. 

But the confusion is that you think that Lunar has to increase the brightness of all monitors at once when you press Brightness Up for example. 

Lunar instead lets the system change the builtin display brightness and then receives and inserts that new brightness into a formula that outputs a new brightness for each monitor. In this way you can have, say, 3 completely different monitors (that usually have different luminosity at the same brightness value) and you can calibrate them by adjusting them manually and have Lunar learn the formula for each.

**Comment by alin23** [comment] 2021-05-31 13:35
Fixed in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

Also check the FAQ about the hotkeys: [How do hotkeys work in Lunar?](https://lunar.fyi#hotkeys)

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*

**Closed by alin23** 2021-05-31 13:35 UTC
