### ISSUE TITLE
Not working with external GPU (eGPU)

### ISSUE THREAD

**Issue by kevinschaich** [alin23/Lunar#65] opened 2020-01-28 06:15 UTC
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Mac Mini (2018)

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell U3219Q

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Computer connected to Razer Core X w/ Radeon VII via USB-C to USB-C
    Radeon VII connected to monitor via Displayport to Displayport

- Using an USB Docking Station or Hub:
    no, but using eGPU

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

# Issue description:
Lunar does not work for me when connected via eGPU. It works when I connect my computer directly to the monitor via USB-C to USB-C.

**Comment by alin23** [comment] 2020-01-28 09:25
Hi @kevinschaich ! Can you please try https://github.com/kfix/ddcctl and see if that works on the eGPU?
That is just a DDC implementation without the bells and whistles of Lunar, so it can help in diagnosing if the problem is Lunar or something related to how the eGPU handles DDC.

**Comment by kevinschaich** [comment] 2020-01-30 02:21
Also not working for me in DCC unfortunately. https://github.com/kfix/ddcctl/issues/60

**Comment by alin23** [comment] 2020-01-30 09:53
Unfortunately, I can't do much about it. I'm no DDC expert and don't really have time to become one 😅 
I'll leave the issue open for others to see, and feel free to update it if there is any progress on the ddcctl side. I would gladly implement any fix and/or accept any PR for this.

**Comment by d4rkd3v1l** [comment] 2020-05-04 06:37
I don't know if/how this helps, but for me Lunar works just great (using an eGPU).

MacBook 13" 2018
Razer Core X with Radeon Vega 64 connected via Belkin 2m TB3-Cable (before via "Razer Cable", worked fine as well)
two 4K Monitors (LG 24UD58-B)

So at least it doesn't seem to be a general eGPU issue, I guess.

**Comment by alin23** [comment] 2020-05-04 09:02
@d4rkd3v1l interesting, thanks for the info!

I guess it's hit and miss with eGPUs. Cable, Mac device and type of connector, all play a role in how the DDC messages are sent through the wire. Hard to say which one of them could fail without having access to different devices/cables to test.

But it's nice to hear that not the eGPU in itself is the problem, but the combination of all of the above factors.

I'll close the issue then as it is not relevant anymore and could spread misinformation.

**Closed by alin23** 2020-05-04 09:02 UTC
