### ISSUE TITLE
Lunar Bug: Menubar hover 

### ISSUE THREAD

**Issue by cwerner1** [alin23/Lunar#286] opened 2021-03-06 07:55 UTC
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    * Macbook Pro 2016

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    * AOC

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    * USB-C-to-Displayport

- Using an USB Docking Station or Hub:
    * no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    * manual

# Issue description:

Thank you for this nice tool!

I have a strange behavour when I move the mouse pointer over the item in the menu bar and click it.

First the options menu opens and then after about half a second, the small settings menu from Lunar opens behind it. 
Please See the Video for reference.

https://user-images.githubusercontent.com/1199614/110199648-a9bf2e80-7e59-11eb-9d8b-1fffa9850ab1.mov

**Comment by alin23** [comment] 2021-03-06 09:51
This is a macOS bug where the click event arrives too late. I'll try a workaround in Lunar 4 but I'll close this as it's not a bug in Lunar's code

**Closed by alin23** 2021-03-06 09:51 UTC
