### ISSUE TITLE
Notch is Enabled but windows have space when disconnected from Monitor.

### ISSUE THREAD

**Issue by namzo** [alin23/Lunar#455] opened 2022-04-30 14:40 UTC
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Macbook Pro 16" 2021

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    LG Ergo 32UN880

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    DisplayPort-to-USB-C

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. Follow through the steps when asked

![Lunar Diagnostics menu item](https://files.lunar.fyi/diagnostics-menu-item.png)

Yes

# Issue description:
When I disconnect from monitor, there is some space at the top of windows that were maximized. I have the "Notch enabled" in the lunar app but it seems the app still resized the windows.

**Comment by alin23** [comment] 2022-04-30 14:41
Can you please send a screenshot? I don't understand what the issue is.

**Comment by alin23** [comment] 2022-04-30 14:44
Closing for #456 

@namzo you can edit the issue, you don't have to create another one

**Closed by alin23** 2022-04-30 14:44 UTC
