### ISSUE TITLE
Monitor does not wake up after macbook goes to sleep

### ISSUE THREAD

**Issue by stephen** [alin23/Lunar#460] opened 2022-05-07 04:11 UTC
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
Macbook Air 2020 (M1)

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
HP z27

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
USB-C-to-USB-C

- Using an USB Docking Station or Hub:
no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
Manual

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. Follow through the steps when asked

![Lunar Diagnostics menu item](https://files.lunar.fyi/diagnostics-menu-item.png)

yes - reads don't work, but writes do

# Issue description:
When put my macbook to sleep while connected to the monitor and come back to it, I've noticed that the monitor does not wake up (ever - waiting up to 1-2 minutes). In this state, replugging the usb-c cable does not help and the physical power button on the monitor does not work. I end up having to unplug/replug the power cable to the monitor for the macbook to connect to the monitor again.

I've tried turning on "wait longer between ddc requests" and turning off "re-apply brightness on screen wake" as mentioned in the FAQ, as well as the gamma profile settings.

During general use, I do not have any issues with flickering/power-off, etc.

**Comment by alin23** [comment] 2022-05-07 06:07
Hi @stephen !

Unfortunately these are not issues that can be caused/fixed by Lunar. Some monitors just do that on receiving DDC commands, but the problem is on their end.

**Closed** 2022-05-07 06:08 UTC
