### ISSUE TITLE
Lunar Diagnostics Report [NO LOGS] [586EA6C431B9B5A424D0DF6FA9F2798079738E00AB73B526DF8F66E9F0193C23] [3.2.3]

### ISSUE THREAD

**Issue by jstader** [alin23/Lunar#204] opened 2020-11-17 20:30 UTC
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    Yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
   Macbook Pro 2019

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   Thunderbolt3 -> Sonnet Breakaway Puck (amd rx560) -> Displayport

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Location

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
   Yes for brightness/contrast, no for volume/mute

# Issue description:
Brightness/Contrast work great in Location and manual mode. Lunar seems to not be able to detect if the clamshell is shut. When in sync mode with the clamshell shut, the brightness/contrast won't change with the hotkeys but the Mac brightness gauge appears. Both monitors are set to unlock as well.

This may be intended functionality and it was easily corrected by switching modes but other users may be confused by this.

Additionally, Volume control does not appear to work with my Del U2718Q monitors via Displayport. I tried with ddcctl as well without success. I will try with HDMI as well later.

**Comment by jstader** [comment] 2020-11-17 21:32
Also, while the native brightness keys work, the slider for brightness in the control center (Big Sur) does not. It currently shows available sidecar displays and a greyed out slider.

That being said I hope this bug report doesn't come across the wrong way! I think the software is great as it is but I wanted to provide some (hopefully beneficial) constructive feedback. I can't believe I just found out about this software. Its layout is beautiful and it looks like it could be part of the native ui!

**Comment by alin23** [comment] 2020-11-18 06:53
Thanks for the report! 

1. If you have Clamshell Mode Detection, then Lunar should automatically switch **from Sync to Manual mode** when the lid is closed completely. If that really doesn't happen let me know so I can investigate it.
![CleanShot 2020-11-18 at 08 44 01@2x](https://user-images.githubusercontent.com/3819725/99494776-42e53a80-297a-11eb-931e-9b832e90e3df.png)
2. If volume control doesn't work in ddcctl then it's a hardware problem. Try other connectors or cables, that's all you can do for now.
3. The sliders for brightness are not programmable by third party apps. I think you got the wrong idea here 😅  that Lunar adds functionality to the OS because Lunar shows the same OSD/gauge as the system when you use the brightness keys. So if the macOS system can't adjust the brightness for your external monitors (either through keys or through the sliders/touchbar) then no app can add that functionality **in the system**. What Lunar does is it listens for brightness keys presses and changes the monitor brightness through DDC, and doesn't forward the key press to the system anymore.

Thanks for the kind words! Let me know if the clamshell detection doesn't work as I have described it above, otherwise I'll close this issue as there doesn't seem to be something fixable in software.

**Comment by alin23** [comment] 2021-05-31 13:31
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*

**Closed by alin23** 2021-05-31 13:31 UTC
Labels: diagnostics
