### ISSUE TITLE
UserNotificationCenter dialogs are not responsive when Lunar is open

### ISSUE THREAD

**Issue by h0tk3y** [alin23/Lunar#466] opened 2022-06-09 19:17 UTC
# Issue details
- Mac device where Lunar is installed: MacBook Pro M1 Max 16" 2021 

- Monitor model: built-in monitor (also occurs with any of my secondary displays)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.): built-in, as well as USB-C and HDMI-to-USB-C

- Using an USB Docking Station or Hub: either way

- Lunar mode used (check it in the top-right corner of the Lunar interface):  Manual as well as Sync

- Tried Lunar Diagnostics? Not applicable, as the issue reproduces with the built-in monitor as well

# Issue description:
With Lunar launched, I can't dismiss the dialogs shown by UserNotificationCenter. Clicking on either option in the dialog has no effect. If I quit Lunar, the dialogs start to work as expected.

Examples of such dialogs are:
* File system permission requests
* AppleScript control requests
* App-specific dialogs (e.g. the one that Tunnelblick shows on the first start)

Steps to reproduce:
* Run Lunar
* Make any other software show the UserNotificationCenter dialog
    * One way to do it is to run `osascript -e 'tell application "Finder" to close windows'`
        * If you need to run it again, reset the permissions e.g. with `/usr/bin/tccutil reset All com.apple.terminal`
* Try to dismiss the dialog by choosing any option
    * The dialog won't disappear, the chosen option won't take effect

NB: Force Quitting the `UserNotificationCenter` process closes the dialog, but the issue happens again if a new dialog appears.

NB: The issue is not specific for the Terminal and `osascript`, I can reproduce it with any other kind of dialog, and I have to quit Lunar to be able to close the dialog.

Screen recording:

https://user-images.githubusercontent.com/1888526/172926006-7a29a422-d647-4044-9d7f-f1d4f33dca19.mp4

**Comment by h0tk3y** [comment] 2022-06-09 19:19
I doubt that the issue is easy to reproduce on any system, given that no one reported it yet. But I've been facing it for some time, over several Lunar versions. I can provide any diagnostic information to help investigating the issue, just tell me what I should do.

**Comment by alin23** [comment] 2022-06-09 19:36
I've actually had the same report a few days ago and in my tests, Lunar didn't affect anything. CleanShot recording was the culprit.

Here's the message that I sent to the other person:

> I stumbled upon something interesting though. I noticed you're using CleanShot X, just like me.
>
>So I just tried to demonstrate to you that I can click normally on those dialogs, but while recording with CleanShot, I couldn't click anymore, just like in your case. But quitting Lunar didn't affect this. What did however fix this, was stopping the screen recording.
>
>You can see my recording here: https://share.cleanshot.com/VaHece
>
>What you can't see is that as soon as I stopped recording, the button was clickable.
>
>This doesn't happen with the system screen recording feature as you can see here: system-screen-recording.mp4
>
>So I guess this might be caused by CleanShot after all.

**Comment by h0tk3y** [comment] 2022-06-09 19:39
Hmm... I don't have CleanShot installed. I'll try to withdraw screen recording permissions from the other apps that I have one by one.

**Comment by h0tk3y** [comment] 2022-06-09 19:49
I removed all screen recording permissions, then restarted with Safe Boot (so no apps launched at login) and reproduced the issue in the same way as in the attached screen recording. It's likely that Lunar has something to do with this. Any ideas what else I could check?

**Comment by alin23** [comment] 2022-06-09 20:11
I'm really stumped by this, I just tested everything I could think of: FaceLight, Gamma, Software Overlay, BlackOut, XDR.

And after every one of those, I made the dialog appear and clicked its buttons without issues.

Are you maybe using an older macOS version that has this bug? It's clearly an OS bug as there's no way for an app to block those buttons from reacting.

**Comment by alin23** [comment] 2022-06-09 20:26
Here's what I experience: 

https://user-images.githubusercontent.com/3819725/172937793-e8c53123-3abe-4686-8ea2-58ef87b71103.mp4

> What else I tried:
> 
>     * Reinstalling Lunar
> 
>     * Resetting the preferences in Lunar
> 
>     * Removing Lunar's permissions
> 
>     * Unregistering all of Lunar's keyboard shortcuts
> 
>     * Turning off notifications from Lunar
> 
> 
> None of that helped with the issue.

At this point, you can be certain it's not a Lunar issue or bug. It's a macOS bug, and something inside Lunar is triggering it, but I can't figure out why without being able to reproduce it.

**Comment by h0tk3y** [comment] 2022-06-09 20:44
Ok, thanks for the research on your side! I'll let you know if I learn something else about this issue.

**Comment by alin23** [comment] 2022-06-09 20:45
Please do as I'm sure you're not the only one experiencing this. I'd like to at least add a workaround if possible.

I'll keep this issue open.

**Comment by alin23** [comment] 2022-06-09 21:14
Huh ok 😅 I'll close the issue then and I'll let people know to **reinstall Lunar from the [official website](https://lunar.fyi/)** if this happens again.

Please let me know here or on Discord if it appears again, maybe we can notice a pattern.

**Comment by h0tk3y** [comment] 2022-06-10 17:09
(Duplicating here my finding that I shared through Discord)

I was able to trigger it again by disabling the notch on the built-in display. Reverting the setting fixes the behavior.
And it seems that rounding corners is affected in the same way for me. Perhaps rounded corners were the culprit the previous time, because it looks very similar to what I had, and I'm quite likely to have experimented with corners rounding.

https://user-images.githubusercontent.com/1888526/173117088-056ba9e9-acdd-400c-b1a8-b61eab729fb2.mp4

**Comment by alin23** [comment] 2022-06-10 21:11
I can't reproduce this, as I have replied on Discord, but I made a change in the hope it might change something.

I've changed the window level for the rounded corners mask window in this alpha: https://files.lunar.fyi/releases/Lunar-5.6.8a1.dmg

For the Notch thing I have no idea what to do, the button is simply changing the native resolution to one that is less tall.

**Comment by HannesGitH** [comment] 2022-06-10 21:49
had the same problem, and i can reliably reproduce (MBP16 as well). Setting corner-radius to 0 also reliably fixes the problem!
Im testing the alpha next.

**Comment by HannesGitH** [comment] 2022-06-10 21:54
ik its mostly a bug in macos itself but i think it would still be great to reopen this issue.

**Comment by alin23** [comment] 2022-06-10 22:13
I'll try to convert the round corners mask window to 4 small corner windows to leave most of the screen free of any kind of overlay. 

Thanks for chiming in and testing!

**Comment by HannesGitH** [comment] 2022-06-10 22:27
allright lmk if i should test another alpha :)

(rounded corners isnt a feature i'd need though, same with hiding the notch, so im happy already) 

the notch toggle btw also causes this behaviour

**Comment by h0tk3y** [comment] 2022-06-11 08:26
@alin23 

Thanks, I tried 5.6.8a1, but the issue is still there.

As to disabling the notch vs changing the resolution: I found out that if I change the built-in display resolution with Lunar to the one that doesn't have the notch (2056 x 1285 @120Hz for me), then there's no issue with the UserNotificationCenter dialogs. 

Is there possibly some difference in how exactly disabling the notch is applied, compared to resolution changing through Lunar Preferences?

**Comment by alin23** [comment] 2022-06-11 08:41
No, disabling the Notch does exactly the same thing as changing the resolution yourself.

The thing is, when the resolution is changing, Lunar has to recreate the overlay windows (if there are any, like the round corner one), and maybe that's what you're experiencing.

**Comment by alin23** [comment] 2022-06-11 08:41
Oh actually, by default, removing the Notch also rounds the corners, I forgot about that. It makes sense now that it's all related to the round corners mask window.

**Comment by alin23** [comment] 2022-06-11 10:25
v5.6.8 was just released with a fix for this

**Closed** 2022-06-11 10:25 UTC

**Comment by h0tk3y** [comment] 2022-06-11 10:52
Thanks! I can confirm that v5.6.8 is working as expected on my machine.
