### ISSUE TITLE
Mac wont recognize monitor anymore

### ISSUE THREAD

**Issue by nothingatall3665** [alin23/Lunar#470] opened 2022-06-27 02:02 UTC
So basically I connected M1 Macbook Air to an older Asus monitor I had through a USB-C hub (HDMI) and then, I started up the app, and when I tried to change my brightness, my monitor disconnected. Now my mac won't recognize my monitor (which still works for my other computer), I've tried following the guide to fix it, but it still won't work.

**Comment by nothingatall3665** [comment] 2022-06-27 02:40
Update: I believe its probably the hub that got messed up, ill update tomorrow once my other one comes in

**Comment by alin23** [comment] 2022-06-27 05:57
@nothingatall3665 Usually a power cycle fixes the issue (unplugging/replugging the monitor into the power outlet, or restarting the Mac). I'll close this issue as it's not a bug in Lunar's code.

The app sends simple "set the brightness to `x%`" commands, if anything goes wrong, it's because either the monitor or the adapters/cables used to connect it are doing something wrong with the DDC signals.

You can read more on how DDC works in Lunar here: https://lunar.fyi/faq#ddc

**Closed by alin23** 2022-06-27 05:57 UTC
