### ISSUE TITLE
Lunar Diagnostics Report [F1A0E09867E2A3B6EBBF1680C3D07DFD1B6A003CFAD0F904FC1E9393D02FADE7] [3.2.3]

### ISSUE THREAD

**Issue by dahjelle** [alin23/Lunar#192] opened 2020-10-15 14:06 UTC
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    Yes.

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro (Retina, 15-inch, Mid 2014)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    miniDisplayPort-to-DisplayPort

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    manual

- Monitor model
    ASUS PB278

# Issue description:
I was hoping the **volume** controls would work. The media keys bring up the HUD with a ⍉. The menu items don't do anything.

Is there something I'm missing?

**Comment by alin23** [comment] 2020-10-15 14:26
Hi @dahjelle !
Do you have **Change monitor volume with volume keys** enabled?
![image](https://user-images.githubusercontent.com/3819725/96142986-53357000-0f0b-11eb-88cb-45fd86e40762.png)

**Comment by dahjelle** [comment] 2020-10-15 14:38
Yup!

![image](https://user-images.githubusercontent.com/156557/96144761-24e37080-0eca-11eb-8233-1cb60add5587.png)

**Comment by alin23** [comment] 2020-10-15 14:53
You also have to have the cursor on the monitor you want to control before pressing the volume keys.
This was a mistake on my part and it will be fixed in the next version.

**Comment by dahjelle** [comment] 2020-10-15 15:20
I do have the cursor on the monitor I'm trying to control. I do have my MacBook open, too. I get the same response regardless of which monitor my cursor is on.

I see I have "Debug Mode" turned on … but I don't know if there are logs sent anywhere that I could supply?

**Comment by alin23** [comment] 2021-05-31 13:32
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*

**Closed by alin23** 2021-05-31 13:32 UTC
Labels: diagnostics
