### ISSUE TITLE
UI keep switching the view when changing brightness offset

### ISSUE THREAD

**Issue by tbrek** [alin23/Lunar#51] opened 2019-12-05 10:07 UTC
As per title and video below

https://vimeo.com/377508944

**Comment by alin23** [comment] 2019-12-05 18:08
@tbrek does the brightness on the Thunderbolt Display change when you change the brightness offset?

**Comment by alin23** [comment] 2019-12-10 09:08
I'll close this as I can't reproduce it anywhere.

**Closed by alin23** 2019-12-10 09:08 UTC

**Comment by tbrek** [comment] 2019-12-10 12:10
> @tbrek does the brightness on the Thunderbolt Display change when you change the brightness offset?

No it does not. It does not control my TD at all. BTW it's connected via USB-C adapter.

**Comment by alin23** [comment] 2019-12-10 15:39
Do you have any way to connect it directly to a port of the Macbook, without an adapter? Usually adapters don't work with Lunar.

You could also try this little app and see if it works: https://github.com/fnesveda/ExternalDisplayBrightness

If that works and Lunar doesn't then I could take a look at the Thunderbolt Display logic inside Lunar to see what's wrong.

Before everything, please install the latest version of Lunar (2.9.10), either by clicking Check For Updates in the Lunar menu bar icon, or by installing it from the official website: https://lunar.fyi
There are a few fixes in the latest version that might help.
