### ISSUE TITLE
LED Color Gain adjustment may damage the HP U32 4K HDR monitor

### ISSUE THREAD

**Issue by pdcastro** [alin23/Lunar#483] opened 2022-08-30 15:40 UTC
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    *MacBook Air M2 (2022)*

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    *HP U32 4K HDR*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *Mainly USB-C-to-USB-C, but also tried HDMI-to-USB-C and DisplayPort-to-USB-c with the same results.*

- Using an USB Docking Station or Hub:
    *No*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Mainly Sensor, but also tried Location and Manual*

- Tried Lunar Diagnostics?
    *Yes*

- Lunar version:
    *5.7.8*

# Issue description:

* Changing the LED Color Gain bars (see screenshot) causes a very strange, scary behaviour of crackling sounds from the monitor, and low frequency (I'd say 5Hz) flickering of _certain areas_ of the screen - I think 4 different areas of the screen. It is a disturbing effect that renders the monitor unusable while the effect is present. The flickering is "very persistent":
  * It persists clicking Lunar's Reset button next to the LED Color Gain bars.
  * It persists clicking Lunar's Full Reset button that "resets all software and hardware settings for this monitor".
  * It persists disconnecting the laptop from the monitor and performing the monitor's Factory Reset through its OSD menu.
  * It persists disconnecting the monitor from all cables including mains power, waiting a few minutes, powering the monitor on, performing another factory reset through the monitor's OSD menu, powering off for a few more minutes, then _connecting the monitor to a different laptop where Lunar was never installed._
  * What fixed the flickering for me was leaving the monitor disconnected from power and all cables overnight (about 8 hours). As if, hypothetically, some relevant super capacitors needed hours to discharge - a matter of electronics rather than software. During this time I had assumed that I would have to return the monitor to HP for repair.

* Besides the flickering, clicking Lunar's Reset button next to the LED Color Gain bars sometimes caused the screen to change overall colors to heavily green or heavily grey, rather than the expected behaviour of restoring the original color gain.

* By the way, the HP U32 4K HDR monitor has "factory color-calibrated accuracy" in its [list of features](https://www8.hp.com/h20195/V2/GetPDF.aspx/c07809696), and I wonder if Lunar's LED Color Gain _persistent_ settings could be throwing away the factory calibration in a way that could not be reset.

<img width="307" alt="Screenshot 2022-08-30 at 15 55 10" src="https://user-images.githubusercontent.com/15091591/187470240-8a3ec104-ffcf-4c82-8f8c-474877db6a35.png">

<img width="326" alt="Screenshot 2022-08-30 at 15 59 35" src="https://user-images.githubusercontent.com/15091591/187473471-fafb78c3-8b06-4c74-9ae0-3150befdd461.png">

I believe that good _hardware_ design should prevent software settings from physically damaging the hardware, especially in a scenario such as Lunar's DDC settings potentially damaging the monitor. Also, a monitor's OSD Factory Reset combined with minutes of disconnection from mains should have fixed whatever software input from the laptop. In this sense, HP is arguably more to blame than Lunar. Nonetheless, pragmatically, I think that Lunar could, say, detect that the monitor is a "HP U32 4K HDR" (this is the string display by Lunar) and then disable the LED Color Gain settings until or unless the flickering issue is better understood.

**Comment by alin23** [comment] 2022-08-30 15:45
Hi @pdcastro 

Unfortunately this is simply a problem with the monitor.

All that those sliders do is to send a `WRITE` DDC command for the `red`, `green` and `blue` gain VCP Codes. Nothing more.

> I wonder if Lunar's LED Color Gain persistent settings could be throwing away the factory calibration in a way that could not be reset.

The persistency here comes from the monitor storing those settings, Lunar is not doing anything to persist them.

There's nothing that can be fixed in Lunar. If the hardware gets damaged from standard commands specified in standard protocols that stabilized 20 years ago, then the hardware is created badly

**Closed by alin23** 2022-08-30 15:45 UTC

**Comment by alin23** [comment] 2022-08-30 15:47
By the way, I also notice you are using the Extended option on color gain. Have you checked if the monitor actually supports values up to 255?

Most monitors only accept values up to 100, which is why that's Lunar's default.

**Comment by pdcastro** [comment] 2022-08-30 16:44
> By the way, I also notice you are using the Extended option on color gain. Have you checked if the monitor actually supports values up to 255?

I can't really say. I have not touched those bars since the "flickering incident". The specific values in the screenshot may have been a result of clicking the button "Read colors from monitor" at some point. Manually changing those bars is a dangerous action with the HP U32 4K HDR monitor, so I am now just leaving them alone.

> There's nothing that can be fixed in Lunar.

Given that we are aware of how badly the HP U32 4K HDR monitor behaves when the color gain is changed, my specific suggestion was for Lunar to disable the LED Color Gain settings for this monitor, for example based on a blacklist of monitors that are known to have firmware/hardware issues. The blacklist could be compiled from user feedback such as this one.

**Comment by alin23** [comment] 2022-08-30 16:59
I understand your concern and your solution sounds good in theory, but the problem is that vendors can't be trusted to not reuse that name for other monitor models. 

Just by checking the Lunar [Monitor Database](https://db.lunar.fyi) (which is by no means an extensive list), we can observe that in 15 samples we already have two different models with the same name. 

![image](https://user-images.githubusercontent.com/3819725/187495551-dfe26561-ec41-4bee-926f-befc57551c31.jpeg)

I guess I could get your exact product ID but even that can be reused across monitors with different firmware features. 

You can read more about how endemic that problem is in my latest article: [Weird monitor bugs people sent me in the last 5 years](https://notes.alinpanaitiu.com/Weird%20monitor%20bugs)

The main point is that this can't and is not supposed to be fixed in Lunar. I'm not going to be able to maintain a hardcoded list of monitors and their edge cases for the rest of Lunar's days.

**Comment by pdcastro** [comment] 2022-08-30 17:31
> By the way, I also notice you are using the Extended option on color gain. Have you checked if the monitor actually supports values up to 255?
>> I can't really say. [...]

For what it is worth, I can improve that answer. The monitor has a number of pre-defined color profiles that can be selected through the OSD menu:

![color-osd](https://user-images.githubusercontent.com/15091591/187504364-e950f5d7-578b-487e-b69e-6717a4a69c4c.jpg)

I have mustered the courage to click Lunar's "Read colors from monitor" button for each of the pre-defined color profiles, and the results are:

- Design for web (sRGB D65): **255/244/217** (Red/Green/Blue)
- Design for print (sRGB D50): **255/158/14**
- Photography (P3 D65): **255/244/217**
- HD video (BT.709): **255/244/217**
- Standard: **227/232/255**
- Gaming: **230/244/255**
- Night: **255/26/245**
- HP Enhance +: **226/232/255**

Values above 100 are capped to 100 if I click the Extended button, so I conclude that the monitor does support values up to 255.

**Comment by alin23** [comment] 2022-08-30 17:41
Yes that means it supports values up to 255. 

The issue is when a monitor uses a color profile, most of the time it doesn't allow external control over the RGB values, and can react in undefined ways if that is attempted. 

As you can read [here](https://lunar.fyi/faq#brightness-not-changing), under every monitor brand section, it's mostly recommended to use the Custom/Standard profile/preset when using DDC.
