### ISSUE TITLE
Add option to change volume on specific monitor instead of currently active one

### ISSUE THREAD

**Issue by inickt** [alin23/Lunar#161] opened 2020-09-01 20:42 UTC
Thanks for making this app! Saw it on HN and its pretty awesome :) 

### Name of the feature

Specific monitor volume control

### What problem does this feature solve?

I have multiple monitors but only use the audio output on one of them. Right now I need to have my cursor on the specific screen my speakers are plugged into to adjust the volume.

### How should the feature work

It would be great if I could either select a monitor to change the volume or if the app could detect my current output and only adjust that monitor. [MonitorControl](https://github.com/MonitorControl/MonitorControl) also has the option of controlling all monitors which would also work, but might be slightly less elegant (and the OSD pops up on all of them)

### Visual description

Probably something just in the settings menu to either pick a specific monitor/determine the currently selected system output

**Comment by alin23** [comment] 2020-09-02 09:01
Yes, I think it was a bad decision to only change the volume where the cursor is. This behaviour makes sense for brightness and contrast, for the volume it makes more sense to just change the volume of the selected audio device.

I'll make sure to include this in the next update.

**Comment by nilsonsales** [comment] 2021-05-26 19:19
> Yes, I think it was a bad decision to only change the volume where the cursor is. This behaviour makes sense for brightness and contrast, for the volume it makes more sense to just change the volume of the selected audio device.
> 
> I'll make sure to include this in the next update.

Any chances to change the volume of other devices other than monitors? Or Lunar doesn't have access to that? I never use my monitor's speakers, but I'd love to use Lunar's short keys to adjust my system's volume.

**Comment by alin23** [comment] 2021-05-26 19:26
@nilsonsales you mean other devices that the system can't adjust natively? I'm not sure I understand your need.

**Comment by nilsonsales** [comment] 2021-05-26 19:33
No, I mean the system's volume. The problem is that I use a Hackintosh, so I don't have the Mac shortcuts. I was thinking about using Lunar shortcuts to control my volume, but it only changes the monitor's volume, which I never use.

**Comment by alin23** [comment] 2021-05-26 19:38
Oh I see. This is not really Lunar's purpose.
You could use something like BetterTouchTool to add arbitrary keyboard shortcuts: 
<img width="997" alt="image" src="https://user-images.githubusercontent.com/3819725/119720748-089dae00-be73-11eb-9d71-4ffe7244d5ec.png">

**Comment by nilsonsales** [comment] 2021-05-26 19:42
You're right. I'll check that other app. Thanks for the recommendation 😀

**Comment by alin23** [comment] 2021-05-31 13:57
Fixed in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*

**Closed by alin23** 2021-05-31 13:57 UTC
