### ISSUE TITLE
Reads internal display brightness as 0.0 after waking up

### ISSUE THREAD

**Issue by SAGV** [alin23/Lunar#195] opened 2020-10-25 10:39 UTC
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 16" 2019, mac os 10.15.7

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    LG Ultrafine 34"

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Usb-C -> DP

- Using an USB Docking Station or Hub:
    Noope

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    Haven't tried

# Issue description:

Very often after going out of sleep mode, lunar assumes that macbook display brightness is 0.0:

![CleanShot 2020-10-25 at 11 34 31](https://user-images.githubusercontent.com/2170509/97104746-879cef00-16b6-11eb-86be-260a9da8dea6.jpg)

Even though it is not :-(
Currently, set to around 70% automatically using brightness sensor.
This sets all external monitors to min brightness.

This started to happen periodically since last month.

I'd love to provide more logs if needed

**Comment by alin23** [comment] 2020-10-25 15:40
Thanks for the detailed report! 

I noticed this too in the last few months, but there has been no update in Lunar's code for more than 6 months so I'm still not sure what causes it. 

I'll try to debug this again in  a few days.

**Comment by pvaibhav** [comment] 2020-11-01 10:40
I'm affected by this bug too :( only unplugging and replugging the monitor seems to fix this.

> there has been no update in Lunar's code for more than 6 months

Just wondering, what does this mean about the "coming soon" badge for external brightness sensors? I'm interested in adding support for i1 Display Pro and Spyder4Pro, if you need help can you point me where to start? Thanks for this awesome tool btw.

**Comment by SAGV** [comment] 2020-11-01 10:49
I noticed that it mostly happens when macbook is awaken after a long sleep while being connected to external monitor the whole period. However, when this happens, the brightness sticks at 0.0 no matter I do and randomly goes away during the day.

**Comment by alin23** [comment] 2020-11-01 17:50
> Just wondering, what does this mean about the "coming soon" badge for external brightness sensors? I'm interested in adding support for i1 Display Pro and Spyder4Pro, if you need help can you point me where to start? Thanks for this awesome tool btw.

Lunar will support external ambient light sensors through serial connection and will have a websocket server implementation so that everyone can implement their own sensor if serial is not enough.

The most important thing I'm working on is a simple firmware + no-solder instructions for a simple and cheap USB light sensor that everyone can make on their own using $4 worth of parts from Amazon/AliExpress.

For now there is no way to add support for i1 Display Pro or Spyder4Pro but I'll look into them and try to add make it easy to support those as well.

**Comment by SAGV** [comment] 2020-11-03 08:42
@alin23 is there any hint from where the bug originates from? Is there anything we can reset to make it work when broken?

**Comment by SAGV** [comment] 2020-11-16 09:37
@alin23 is there anything we can do to help in solving this issue? 

I can also confirm it happening on Big Sur. And apparently that it is happening way less this some other screen I'm using — not sure why the screen is the issue but I have LG Ultrafine 34" and LG Ultrafine 38", it almost never happens with the 38". I tried switching cables (first uses DP->Usb-c and second HDMI->Usb-c) but the cable is not the issue.

However, I was able to fix the sensor (till next sleep?) by switching cables from DB->Usb-c to Usb-c->Usb-c.

**Comment by alin23** [comment] 2020-11-16 09:43
I'm still debugging this when I have time for Lunar development. It takes time because I can't reproduce it consistently and I have to constantly run Lunar in a debugger and wait for the problem to appear.

For my case, changing the mode from Sync to Location to Manual and back to Sync always solves this issue, so that might be a faster workaround than reconnecting the cables. Other than that, there's not much else you can do until I release a new version.

**Comment by SAGV** [comment] 2020-11-16 09:50
Hmm, I'm facing this issue almost every morning. If it is easy to run the app in the debugger, I can do so later this week and send you logs — maybe a short screen recording by you aka "how to run the app in the debugger" can help.

I am not a native mac developer but I played with ios apps for a while and have dev env prepared so shouldn't be hard for me.

**Comment by pvaibhav** [comment] 2020-11-24 15:21
I tried to fork and build the project, but currently stuck because [this NSPageControl library](https://github.com/nerd0geek1/NSPageControl) can't be built on Xcode 12 (needs Swift v3?).

Anyway, I think I've narrowed down the problem: on resume, it's possible that the display IDs get reassigned, i.e. the internal display which was display 0 could become display 1 and the external could become display 0.

You can check this by installing the `brightness` command: `brew install brightness` and then run `brightness -l`. In my case, Lunar is reading 0.0 for the brightness, presumably checking only display 0. But the internal one is (now) display 1:

```
❯ brightness -l
display 0: main, active, awake, online, external, ID 0x1b5d9b4e
brightness: failed to get brightness of display 0x1b5d9b4e (error -536870201)
display 1: active, awake, online, built-in, ID 0x4280f80
display 1: brightness 0.397461
```

@alin23  I suggest looping over all the displays and using the first valid brightness value.

**Comment by alin23** [comment] 2021-05-31 13:36
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*

**Closed by alin23** 2021-05-31 13:36 UTC
