### ISSUE TITLE
Resolution of Inbuilt weird after disconnecting monitor

### ISSUE THREAD

**Issue by ThoughtfulDev** [alin23/Lunar#448] opened 2022-04-07 05:28 UTC
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Macbook Air M1 2020

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    DELL U4919DW

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C-to-USB-C

- Using an USB Docking Station or Hub:
   Yes, CalDigit Thunderbolt 4 Element Hub

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Auto: Location

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. Follow through the steps when asked

![Lunar Diagnostics menu item](https://files.lunar.fyi/diagnostics-menu-item.png)

    No

# Issue description:
Brightness etc works fine. I wanted to use the Light sensor from my Macbook with the Lid open in combination with the Auto Blackout mode so that the MB display gets dark while the lid is open and the external monitor is connected.
This works as expected but when i disconnect the monitor from the Macbook then the internal screen lightens again but the resolution is really a non-native one on the internal display and i cant select any other in Lunar.

I have to quit Lunar, go into the display settings in MacOS and then change the resolution there to native.
This only happens when using the blackout mode.

Maybe its an issue with the huge resolution of my external display(5120x1440).
Otherwise i might have to use a external Light sensor from my Home Assistant.

**Comment by alin23** [comment] 2022-04-07 05:30
Hi @ThoughtfulDev !

What you see is mirroring mode being enabled, not a bad resolution. If you disconnect your external monitor, Lunar will disable BlackOut and mirroring automatically.

You can also disable it manually from System Preferences -> Displays or with the Cmd+BrightnessDown hotkey.

**Comment by alin23** [comment] 2022-04-07 05:32
Oh I just noticed you said this happens **after** you disconnect the monitor. Can you post a short video with your phone reproducing this bug? I'm not experiencing it

**Comment by ThoughtfulDev** [comment] 2022-04-07 05:55
https://www.youtube.com/watch?v=RxOXxK2B9TE
Set the video to not listed.

**Comment by alin23** [comment] 2022-04-07 05:59
Oh wow, what the heck.. 

I'm 99% sure this is not a Lunar bug. Here's what BlackOut does:

1. Sets the built-in brightness to absolute 0 (this turns off the display backlight completely on MacBooks)
2. Alters the RGB Gamma tables of the display so that all color formulas result in 0 (pitch black)
3. Mirrors the built-in to the visible external monitor so that the screen is basically disabled and all windows move to the external monitor

On disconnection, it just reverts the above steps, not changing the resolution in any way.

This is probably a system bug that we have to work around. I'll post a beta with a possible work around in a few minutes.

**Comment by ThoughtfulDev** [comment] 2022-04-07 06:07
Sure no worries. Thanks for the quick help by the way

**Comment by alin23** [comment] 2022-04-07 06:12
Here it is: https://files.lunar.fyi/Lunar-5.5.5-beta1.zip

Let me know if it still reproduces.

**Comment by ThoughtfulDev** [comment] 2022-04-07 07:25
Yes still same issue.
I saw that when the resolution is "wrong" it shows in Lunar as 1400x900 but when i then change it manually in display settings of macos it shows as 1400x900@60Hz in Lunar.

**Comment by alin23** [comment] 2022-04-07 10:45
Can you check this one: https://files.lunar.fyi/Lunar-5.5.5-beta2.zip

I've added logic to save the last resolution before mirroring, and force apply it after mirroring is ended.

**Comment by ThoughtfulDev** [comment] 2022-04-07 11:38
Tried it. Same issue.
I have set both to "Auto" and didnt change any setting.
What i usually do is (when i dont have the issue and blackout disabled).

1. open the laptop
2. connect the monitor
3. close lid

If you need some diagnostics or debug logs - im happy to help.

**Comment by alin23** [comment] 2022-04-07 11:44
Wait, after connecting the external monitor and blackout is automatically enabled, you close the lid?

**Comment by alin23** [comment] 2022-04-07 12:00
Can you send me the log file from `~/Library/Caches/Lunar/swiftybeaver.log` ?

I'd also want to understand how you're using this feature, because closing the lid while using Blackout is not the correct way to use it (most likely I'm just misunderstanding). 

Also, what do you mean by "set both to Auto"?

**Comment by ThoughtfulDev** [comment] 2022-04-07 12:26
No with autoblackout disabled i close the lid (cause im using location and no sensor).

With auto blackout enabled i leave the lid open for the sensor to work obviously.

ny "auto" i mean the mode (location, sensor, manual etc). I just leave it at auto and let it choose its best.

i uploaded the log to my onedrive: https://1drv.ms/u/s!AoZZDrtOqlp0ftlZhXzP57gSxhw?e=c2frMB

**Comment by alin23** [comment] 2022-04-07 17:58
Here's another attempt: https://files.lunar.fyi/Lunar-5.5.5-beta3.zip

Looks like the resolution was being applied but not commited to the screen configuration.

Thanks for clarifying everything above! I wasn't getting the "both to Auto" sentence because the mode is not per-monitor, it is per app. So setting the mode to Auto can only be done once, it's a global setting.

**Comment by ThoughtfulDev** [comment] 2022-04-07 18:30
Tried it but still the same weird resolution. For me it looks like its for some reason a weird aspect ratio? 4:3 is what it looks like to me.

And i noticed something else. No idea if its an isolated issue or has something to do with this but when i use the auto blackout and then disconnect my screen and "fix the macbook resolution" and turn off blackout and after connect my external monitor again the monitor brightness and contrast is on "Manual mode" and i have to change it to Auto: Location or manually to location. This only happens after i disable blackout and then reconnect the monitor.

But if this has nothing to do with this issue here its fine my main issue is still the resolution.

Btw appreciate your effort in helping me out so fast :)
If you need the logs i can just delete the log file (i assume) and reproduce the issue tomorrow , so you have a fresh log?

**Comment by alin23** [comment] 2022-04-07 18:32
It's ok if you just send the logs again :) Compress them before to save some bandwidth.

It's possible that another code path was taken this time.

**Comment by ThoughtfulDev** [comment] 2022-04-08 08:06
https://1drv.ms/u/s!AoZZDrtOqlp0f4nhDYzztpuAN4Y?e=Ucs3Sf
Here the new log. Tried it at 10:00 till 10:02AM (UTC+02)

**Comment by alin23** [comment] 2022-04-08 08:31
Hmm, looks like it's working properly but the system is not actually doing anything since you report still having the same issue:


```swift
10:00:51.997 INFO Pro.saveModeBeforeMirroring():1800 - Got display mode before mirroring: <CGDisplayMode 0x60000081e8c0> [{
    BitsPerPixel = 32;
    BitsPerSample = 10;
    DepthFormat = 8;
    Height = 900;
    IODisplayModeID = 8;
    IOFlags = 7;
    Mode = 8;
    PixelEncoding = "--RRRRRRRRRRGGGGGGGGGGBBBBBBBBBB";
    RefreshRate = 60;
    SamplesPerPixel = 3;
    UsableForDesktopGUI = 1;
    Width = 1440;
    kCGDisplayBytesPerRow = 11520;
    kCGDisplayHorizontalResolution = 255;
    kCGDisplayModeIsInterlaced = 0;
    kCGDisplayModeIsSafeForHardware = 1;
    kCGDisplayModeIsStretched = 0;
    kCGDisplayModeIsTelevisionOutput = 0;
    kCGDisplayModeIsUnavailable = 0;
    kCGDisplayModeSuitableForUI = 1;
    kCGDisplayPixelsHigh = 1800;
    kCGDisplayPixelsWide = 2880;
    kCGDisplayResolution = 2;
    kCGDisplayVerticalResolution = 255;
}]

...

10:01:05.445 INFO DisplayController.resetDisplayList():1323 - Disabling BlackOut for Built-in [ID 1]: blackOutEnabled=true mirror=0 mirrorExists=false

10:01:05.450 INFO Pro.resetModeBeforeMirroring():1806 - Setting display mode we saved before mirroring: <CGDisplayMode 0x60000081e8c0> [{
    BitsPerPixel = 32;
    BitsPerSample = 10;
    DepthFormat = 8;
    Height = 900;
    IODisplayModeID = 8;
    IOFlags = 7;
    Mode = 8;
    PixelEncoding = "--RRRRRRRRRRGGGGGGGGGGBBBBBBBBBB";
    RefreshRate = 60;
    SamplesPerPixel = 3;
    UsableForDesktopGUI = 1;
    Width = 1440;
    kCGDisplayBytesPerRow = 11520;
    kCGDisplayHorizontalResolution = 255;
    kCGDisplayModeIsInterlaced = 0;
    kCGDisplayModeIsSafeForHardware = 1;
    kCGDisplayModeIsStretched = 0;
    kCGDisplayModeIsTelevisionOutput = 0;
    kCGDisplayModeIsUnavailable = 0;
    kCGDisplayModeSuitableForUI = 1;
    kCGDisplayPixelsHigh = 1800;
    kCGDisplayPixelsWide = 2880;
    kCGDisplayResolution = 2;
    kCGDisplayVerticalResolution = 255;
}]
```

----

Here's my last attempt at this: https://files.lunar.fyi/Lunar-5.5.5-beta4.zip

What's different:
1. It adds a 5-second delay before resetting the resolution
2. It uses the private MonitorPanel macOS framework, which is the same one that's used by System Preferences (that's so we stay as close as possible to what the system does when changing resolutions)

**Comment by ThoughtfulDev** [comment] 2022-04-08 09:30
Still doesnt work.
But i saw it changing in Lunar. When i disconnect the monitor it goes from 1440x900 to 1440x900@60Hz and then when i change it via display system settings back to normal Lunar shows 1440x900@60 Hertz.
So Lunar is reverting the resolution but apparently the "wrong" one? Hz vs Hertz spelled out.

new log: https://1drv.ms/u/s!AoZZDrtOqlp0f4nhDYzztpuAN4Y?e=Q7YR11

**Comment by alin23** [comment] 2022-04-08 09:35
No, the Hz vs Hertz it's just a visual thing where Lunar hasn't yet got to the styling of the menu item.

I'm looking at the logs right now

**Comment by alin23** [comment] 2022-04-08 10:00
Ok last last try 😅

This time I'm setting the resolution `ID` instead of the resolution full object, in case the object is not valid anymore after reconfiguration.

https://files.lunar.fyi/Lunar-5.5.5-beta5.zip

**Comment by ThoughtfulDev** [comment] 2022-04-08 10:19
new log: https://1drv.ms/u/s!AoZZDrtOqlp0f4nhDYzztpuAN4Y?e=c6vvDS

still same issue. I also reset both monitor settings in Lunar and set everything to default with still no solution.
Even without the thunderbolt dock the issue persists.

If this doesnt work its fine i might use one of the few ESPs i have here or my HASS light sensor as a source.

**Comment by alin23** [comment] 2022-04-08 10:32
Yeah, sorry. It looks like this is just a bad macOS bug, as it ignores everything that Lunar tries in changing resolutions.

I'll close this for now. If you want to use HomeAssistant as the sensor, There's already a server implementation here that can act as a Lunar sensor: https://github.com/alin23/lunarsensor#reading-from-a-homeassistant-lux-sensor

**Closed by alin23** 2022-04-08 10:32 UTC
