### ISSUE TITLE
Lunar Diagnostics Report [https://transfer.sh/3EYBq/lunar.log.enc] [E4A480FC0CE0330F5C826B733B49E5B7C32F99F11BD8988B16A24DBB540C6307] [3.1.3]

### ISSUE THREAD

**Issue by salayidin** [alin23/Lunar#87] opened 2020-03-29 14:05 UTC
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
   yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
   MacBook Pro (16-inch, 2019)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   USB-C-to-DisplayPort

- Using an USB Docking Station or Hub:
   no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
   Location

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*write a short description of what doesn't work as expected*
when i swtich it to Location Mode, it will became 100% brightness and 100% contrast while one minute。

**Comment by alin23** [comment] 2020-04-23 09:59
@salayidin I'm sorry but I can't reproduce this error at all and can't find anything in the code that could cause this. I suspect it is something related to your setup as I haven't got any other reports with the same issue.

I don't know what else to do about this issue, so I'm going to close it.

**Closed by alin23** 2020-04-23 09:59 UTC
Labels: diagnostics
