### ISSUE TITLE
Can only control one out of two HDMI monitors from Sabrent Thunderbolt 3 to Dual HDMI adapter

### ISSUE THREAD

**Issue by gescarra** [alin23/Lunar#335] opened 2021-06-02 13:51 UTC
Issue reported on #301 still happens on Lunar 4

# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 16" 2019

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Samsung S27E510 x 3

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Sabrent TB3 to Dual HDMI 2.0, USB-C to HDMI

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    100%. I can read and change brightness on all 3 monitors through ddcctl.

# Issue description:
Lunar will only control 2/3 monitors at a time. It sees all of them but can't control one of the two displays out of the Sabrent TB3 dual HDMI adapter. ddcctl controls them without issue.

**Comment by alin23** [comment] 2021-06-02 14:04
Please click on `Open Lunar Diagnostics` in the Lunar menu and press keys when prompted to finish the diagnostics process for all monitors.

After that, click on **Send Diagnostics** to send all the technical data needed for me to debug this. Thanks!

**Comment by alin23** [comment] 2021-06-03 18:14
@gescarra could you help me with some diagnostics on this?

**Comment by alin23** [comment] 2021-06-15 21:20
@gescarra Could you try Lunar 4.1.0 and see if this still occurs?

**Comment by gescarra** [comment] 2021-06-16 18:54
Tried Lunar 4.1.3 and still the same issue, only one of the two screens off the Thunderbolt adapter can be controlled. I just sent the diagnostics over. One thing to mention during the diagnostics test is that Lunar showed "0 out of 4 tries seemed to reach the monitor", but then it tried ddcctl and it changed the brightness of the wrong monitor. I'm thinking Monitor ID's are getting mixed up somewhere and model number is being used instead. All monitors are the same model.

**Comment by alin23** [comment] 2021-06-16 19:08
I'm 99% sure the problem here is the adapter. All the below points are signs of an adapter that only exposes DDC for one of the HDMI ports:

1. One of the monitors doesn't have an I2C controller
```
• ID: 188963731
• EDID Name: S27E510
• I2C Controller: 28423
```
```
• ID: 188963732
• EDID Name: S27E510
• I2C Controller: NONE
```

2. ddcctl controls the wrong monitor
    * The function for controlling brightness only accepts monitor IDs
    * The model number can't to be used in any way for controlling DDC
    * The problem is that macOS doesn't have a way to get the ID for a monitor, and ddcctl tries to find the correct ID by matching the monitor name, model and serial. That's why it probably receives the ID of the other monitor.

I'll close this as it is definitely a hardware issue that can't be fixed in software. Without a separate I2C controller, a monitor can't be controlled in any way through DDC.

For the non-controllable monitor, you can disable DDC and use Gamma if you want any kind of brightness control:

![Shot_Lunar__1VdkBnRZ](https://user-images.githubusercontent.com/3819725/122278072-3cf31000-ceef-11eb-8564-1bbb870f1886.png)

If you really want DDC for both monitors, you'll have to change your adapter. Most adapters that provide more than one HDMI/DP connector have this problem. It's better to use a separate adapter for each monitor.

**Comment by gescarra** [comment] 2021-06-16 19:35
Thank you @alin23, but.... ddcctl (outside of Lunar) can control all 3 monitors, the diagnostics tool picks the wrong monitor when validating. That's the interesting bit and why i think the issue is with an ID somewhere (identifying the port vs. the screen?).

If ddcctl from commandline works on all 3 screens this is not a hardware issue and it's just an identification issue IMO.

**Comment by alin23** [comment] 2021-06-16 19:38
Oh that's interesting. Have you compiled ddcctl from latest master?

**Comment by alin23** [comment] 2021-06-16 19:46
Here's the universal ddcctl binary that Lunar uses: https://static.alinpanaitiu.com/ddcctl

I just compiled it from latest master branch. Could you try and see if it works for you?

If it has the same problems, please let me know what ddcctl binary are you using and if you can, send it to me.

**Comment by alin23** [comment] 2021-06-16 20:52
@gescarra we can move the discussion to Lunar's Discord channel to solve this quicker: https://discord.gg/dJPHpWgAhV

**Closed** 2021-06-17 16:04 UTC
