### ISSUE TITLE
Minimize logging amount

### ISSUE THREAD

**Issue by gezihuzi** [alin23/Lunar#471] opened 2022-06-30 06:51 UTC
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    MacBook Pro 14 2021, M1 Pro

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    LG 27UP850N, LG 29WK500-P

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C-to-USB-C, HDMI-to-USB-C

- Using an USB Docking Station or Hub:
    Docking Hub

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sensor

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. Follow through the steps when asked

![Lunar Diagnostics menu item](https://files.lunar.fyi/diagnostics-menu-item.png)

    yes

# Issue description:
I used the application cleanup tool to detect junk files and found a log file of nearly 18GB under Lunar's cache path.
<img width="688" alt="iShot_2022-06-30_14 37 20" src="https://user-images.githubusercontent.com/12797966/176611458-d6ce9531-ed57-4d1e-bc1a-74bd93ef03da.png">
<img width="650" alt="iShot_2022-06-30_14 37 02" src="https://user-images.githubusercontent.com/12797966/176611466-beec1454-f39c-4b5e-a872-834b4ba0b698.png">

**Comment by alin23** [comment] 2022-06-30 06:54
Thanks for the report!

Lunar already disables Verbose Logging on each startup to minimize the changes of this happening.  It's probably caused by a monitor constantly refusing DDC and Lunar trying to find its DDC service in a loop which can print a lot of text because of the large ioreg trees. 

I'll move those messages to the `verbose` level.

**Comment by alin23** [comment] 2022-06-30 10:21
Fixed in https://github.com/alin23/Lunar/commit/6425f9281d1f2f8532123ca7a689c1649be29d42

Will be released in the next version.

**Closed by alin23** 2022-06-30 10:21 UTC
