### ISSUE TITLE
Sync Mode does not work on iMac (late 2013)

### ISSUE THREAD

**Issue by Enaah** [alin23/Lunar#90] opened 2020-04-07 22:15 UTC
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    iMac Late 2013 - A1418 (EMC 2638) (macOS Catalina (10.15.4))

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
   Dellp2416D (24" 2k Monitor)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Display-Miniport (Thunderbolt) to Displayport

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync-Mode

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*write a short description of what doesn't work as expected*
The Sync-Mode does not work.  
It Works with my Macbook Retina 13" (Mid 2015), with the same Screen.

If you have any suggestions I would be thankful.

Thanks for the great product!

**Comment by alin23** [comment] 2020-04-08 09:16
Hi @Enaah 
1. Does the iMac have `Automatically adjust brightness` enabled?
![image](https://user-images.githubusercontent.com/3819725/78766297-c32dd100-7991-11ea-9fe3-4b0681d363b5.png)


2. And does it adjust the brightness on your iMac when you cover the ambient light sensor?
![image](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/imac/imac-2012-2015-front-view-tech-spec.png)
3. Can Lunar change your Dell monitor's brightness in other modes? (Location or Manual)

If yes, then can you please run the following commands in the terminal twice (_before and after covering the light sensor_) and post the output here?

1. Run this once to install a needed utility:
```shell
brew install ripgrep
```
2. Run this with the light sensor **not covered** and copy the output:
```shell
ioreg -c AppleBacklightDisplay | rg -o '"[^"]*brightness[^}]+"value"=[0-9]+}'
```
3. Run this again with the light sensor **covered** and copy the output:
```shell
ioreg -c AppleBacklightDisplay | rg -o '"[^"]*brightness[^}]+"value"=[0-9]+}'
```

**Comment by Enaah** [comment] 2020-04-08 11:49
Thanks for the quick response!

> 1. Does the iMac have Automatically adjust brightness enabled?

It was enabled, I disabled it and it had no effect.  

> 2. And does it adjust the brightness on your iMac when you cover the ambient light sensor?
 
No, it had no effect.

> 3. Can Lunar change your Dell monitor's brightness in other modes? (Location or Manual)

Yes *Manuel* and *Location* Modes are working.

> 2. Run this with the light sensor **not covered** and copy the output:

```
"linear-brightness-probe"={"min"=0,"max"=65535,"value"=656}
"linear-brightness"={"min"=0,"max"=65535,"value"=45950}
"brightness-fade"={"min"=0,"max"=65534,"value"=0}
"usable-linear-brightness"={"min"=2163,"max"=65535,"value"=45950}
"brightness"={"min"=0,"max"=65535,"value"=45950}
"brightness-probe"={"min"=0,"max"=65535,"value"=656}
```


> 3. Run this again with the light sensor **covered** and copy the output:

```
"linear-brightness-probe"={"min"=0,"max"=65535,"value"=656}
"linear-brightness"={"min"=0,"max"=65535,"value"=45950}
"brightness-fade"={"min"=0,"max"=65534,"value"=0}
"usable-linear-brightness"={"min"=2163,"max"=65535,"value"=45950}
"brightness"={"min"=0,"max"=65535,"value"=45950}
"brightness-probe"={"min"=0,"max"=65535,"value"=656}
```

I had `Automatically adjust brightness` enabled and once disabled, no effect on the output.
Is my Light-sensor broken (because the output did not change)?


Thanks in advance!

**Comment by alin23** [comment] 2020-04-08 11:59
Yes, looks like there's an issue with your light sensor. Sync mode reacts to built-in display brightness changes, which in turn are caused by the light sensor readings by the system.

You can try to reset SMC to see if it makes any difference: https://support.apple.com/en-us/HT201295#reset

**Comment by alin23** [comment] 2020-04-08 12:00
I'll close this as it is not an issue with Lunar, but we can keep the discussion going.

**Comment by Enaah** [comment] 2020-04-13 12:58
Hey, I tried to reset the SMC, but nothing changed.  
I have changed the LCD last week (because it was broken) but nothing changed, I guess the light sensor is just broken.  
If it's not broken the output from `ioreg -c AppleBacklightDisplay | rg -o '"[^"]*brightness[^}]+"value"=[0-9]+}'` should have changed, right?

**Comment by alin23** [comment] 2020-04-13 13:01
Yes, those values are the built-in monitor brightness values reported by the system. 

If your built-in monitor brightness doesn't change when you cover/uncover the light sensor then it must not be working.

**Comment by Enaah** [comment] 2020-04-13 14:05
Thanks.  
On the MacBook it's working (and _Sync Mode_ aswell).  
For my Information: Could you explain how/why the light sensor ist connected/necessary for _Sync Mode_? 🙂

**Comment by alin23** [comment] 2020-04-13 14:10
Sync Mode works by listening for brightness changes on the built-in monitor and _synchronising_ those changes to the external monitors.

Of course that makes sense only if the built-in monitor already reacts to the ambient light around it.

Sync mode can work without the light sensor too. If you manually change the built-in monitor brightness, Lunar should sync that to the external monitor. It just isn't that useful.

**Comment by Enaah** [comment] 2020-04-13 14:32
Thanks for the information.

> Sync mode can work without the light sensor too. If you manually change the built-in monitor brightness, Lunar should sync that to the external monitor. It just isn't that useful.

I only want and use that with Luna 😅
So this should be working even if the _light sensor_ is broken?
Because it doesn't. The brightness of the second Monitor gets really dark and changes only effect the iMac Screen.

**Comment by alin23** [comment] 2020-04-13 14:38
Oh I had no idea you want to use it this way. Can you try to see if [ddcctl](https://github.com/kfix/ddcctl) works for you?

Also check if the `ioreg` commands report different values after you change the built-in monitor brightness manually.

If the steps above work as expected, can you send me the log found at `~/Library/Caches/Lunar/swiftybeaver.log` ? I'm going to need more details about what Lunar is doing behind the scenes on your machine.

**Comment by Enaah** [comment] 2020-04-14 18:56
Hey,
I've managed to get different output with the `ioreg`-Command on my MacBook and retried it with my iMac and it worked aswell.

`ioreg -c AppleBacklightDisplay | rg -o '"[^"]*brightness[^}]+"value"=[0-9]+}'`

> Run this with the light sensor not covered and copy the output:

```sh
"linear-brightness-probe"={"min"=0,"max"=65535,"value"=656}
"linear-brightness"={"min"=0,"max"=65535,"value"=65535}
"brightness-fade"={"min"=0,"max"=65534,"value"=0}
"usable-linear-brightness"={"min"=2163,"max"=65535,"value"=65535}
"brightness"={"min"=0,"max"=65535,"value"=65535}
"brightness-probe"={"min"=0,"max"=65535,"value"=656}
```
> Run this with the light sensor covered and copy the output:

```sh
"linear-brightness-probe"={"min"=0,"max"=65535,"value"=656}
"linear-brightness"={"min"=0,"max"=65535,"value"=51852}
"brightness-fade"={"min"=0,"max"=65534,"value"=0}
"usable-linear-brightness"={"min"=2163,"max"=65535,"value"=51852}
"brightness"={"min"=0,"max"=65535,"value"=51852}
"brightness-probe"={"min"=0,"max"=65535,"value"=656}
```

But still, "Sync" is not working correctly. 

here the Output of `~/Library/Caches/Lunar/swiftybeaver.log`
```log
23:58:01.091 INFO BrightnessAdapter.addSentryData():231 - Creating Sentry extra context
23:58:01.096 INFO AppDelegate.applicationDidFinishLaunching():662 - Setting log path to /Users/mathishaane/Library/Caches/Lunar/swiftybeaver.log
23:58:01.191 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 6
	Contrast: 28
23:58:09.268 INFO ModernWindowController.windowWillClose():14 - Window closing
23:58:24.033 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 6
	Contrast: 28
00:01:09.250 INFO AppDelegate.applicationWillTerminate():688 - Going down
00:01:19.064 INFO BrightnessAdapter.addSentryData():231 - Creating Sentry extra context
00:01:19.068 INFO AppDelegate.applicationDidFinishLaunching():662 - Setting log path to /Users/mathishaane/Library/Caches/Lunar/swiftybeaver.log
00:02:01.766 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 5
	Contrast: 20
00:02:04.839 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 6
	Contrast: 28
00:08:03.639 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 6
	Contrast: 28
00:08:12.506 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 6
	Contrast: 28
00:12:59.547 INFO BrightnessAdapter.manageClamshellMode():288 - Lid closed: false
00:12:59.549 INFO BrightnessAdapter.addSentryData():231 - Creating Sentry extra context
00:14:30.176 INFO BrightnessAdapter.manageClamshellMode():288 - Lid closed: false
00:14:30.196 INFO BrightnessAdapter.addSentryData():231 - Creating Sentry extra context
02:00:15.474 INFO AppDelegate.applicationWillTerminate():688 - Going down
13:27:35.672 INFO BrightnessAdapter.addSentryData():231 - Creating Sentry extra context
13:27:35.677 INFO AppDelegate.applicationDidFinishLaunching():662 - Setting log path to /Users/mathishaane/Library/Caches/Lunar/swiftybeaver.log
13:29:54.358 INFO BrightnessAdapter.manageClamshellMode():288 - Lid closed: false
13:29:54.385 INFO BrightnessAdapter.addSentryData():231 - Creating Sentry extra context
13:36:23.908 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 6
	Contrast: 28
13:37:52.664 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 7
	Contrast: 28
13:37:53.165 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 8
	Contrast: 28
13:37:53.249 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 10
	Contrast: 28
13:37:53.333 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 12
	Contrast: 28
13:37:53.417 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 14
	Contrast: 28
13:37:53.500 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 17
	Contrast: 28
13:37:53.584 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 20
	Contrast: 28
13:37:53.668 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 24
	Contrast: 28
13:37:53.751 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 29
	Contrast: 28
13:37:53.836 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 35
	Contrast: 28
13:37:53.920 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 42
	Contrast: 28
13:37:54.004 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 50
	Contrast: 28
13:37:54.088 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 60
	Contrast: 28
13:37:54.172 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 72
	Contrast: 28
13:37:54.258 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 74
	Contrast: 28
13:38:13.330 INFO ModernWindowController.windowWillClose():14 - Window closing
02:03:27.438 INFO BrightnessAdapter.addSentryData():231 - Creating Sentry extra context
02:03:27.480 INFO AppDelegate.applicationDidFinishLaunching():662 - Setting log path to /Users/mathishaane/Library/Caches/Lunar/swiftybeaver.log
02:03:27.671 ERROR AppDelegate.locationManager():717 - Location manager failed with error: Error Domain=kCLErrorDomain Code=0 "(null)"
16:45:16.787 INFO BrightnessAdapter.addSentryData():231 - Creating Sentry extra context
16:45:16.791 INFO AppDelegate.applicationDidFinishLaunching():662 - Setting log path to /Users/mathishaane/Library/Caches/Lunar/swiftybeaver.log
02:19:30.596 INFO BrightnessAdapter.addSentryData():231 - Creating Sentry extra context
02:19:30.606 INFO AppDelegate.applicationDidFinishLaunching():662 - Setting log path to /Users/mathishaane/Library/Caches/Lunar/swiftybeaver.log
10:22:15.173 INFO AppDelegate.applicationWillTerminate():688 - Going down
20:12:39.067 INFO BrightnessAdapter.addSentryData():231 - Creating Sentry extra context
20:12:39.072 INFO AppDelegate.applicationDidFinishLaunching():662 - Setting log path to /Users/mathishaane/Library/Caches/Lunar/swiftybeaver.log
20:18:23.489 INFO AppDelegate.applicationWillTerminate():688 - Going down
21:09:31.584 INFO BrightnessAdapter.addSentryData():231 - Creating Sentry extra context
21:09:31.588 INFO AppDelegate.applicationDidFinishLaunching():662 - Setting log path to /Users/mathishaane/Library/Caches/Lunar/swiftybeaver.log
21:09:31.730 ERROR AppDelegate.locationManager():717 - Location manager failed with error: Error Domain=kCLErrorDomain Code=0 "(null)"
21:10:16.670 INFO AppDelegate.applicationWillTerminate():688 - Going down
21:23:08.089 INFO BrightnessAdapter.addSentryData():231 - Creating Sentry extra context
21:23:08.094 INFO AppDelegate.applicationDidFinishLaunching():662 - Setting log path to /Users/mathishaane/Library/Caches/Lunar/swiftybeaver.log
21:23:30.220 INFO BrightnessAdapter.manageClamshellMode():288 - Lid closed: false
21:23:30.238 INFO BrightnessAdapter.addSentryData():231 - Creating Sentry extra context
21:23:56.488 INFO BrightnessAdapter.manageClamshellMode():288 - Lid closed: false
21:23:56.509 INFO BrightnessAdapter.addSentryData():231 - Creating Sentry extra context
21:24:07.733 INFO Display.adapt():1029 -
DELL P2416D:
	Brightness: 74
	Contrast: 28
12:40:37.116 INFO BrightnessAdapter.addSentryData():231 - Creating Sentry extra context
12:40:37.127 INFO AppDelegate.applicationDidFinishLaunching():662 - Setting log path to /Users/mathishaane/Library/Caches/Lunar/swiftybeaver.log
14:36:37.083 INFO BrightnessAdapter.manageClamshellMode():288 - Lid closed: false
14:36:37.106 INFO BrightnessAdapter.addSentryData():231 - Creating Sentry extra context
02:39:46.959 INFO AppDelegate.applicationWillTerminate():688 - Going down
17:01:45.759 INFO BrightnessAdapter.addSentryData():231 - Creating Sentry extra context
17:01:45.763 INFO AppDelegate.applicationDidFinishLaunching():662 - Setting log path to /Users/mathishaane/Library/Caches/Lunar/swiftybeaver.log
17:06:49.096 INFO AppDelegate.applicationWillTerminate():688 - Going down
17:06:50.899 INFO Util.getSerialNumberHash():57 - D477EF8AAB68518670C778D50B93E2197865440342519014868C3C20481FA1D1
17:06:50.907 INFO BrightnessAdapter.addSentryData():234 - Creating Sentry extra context
17:06:50.909 INFO AppDelegate.applicationDidFinishLaunching():707 - Setting log path to /Users/mathishaane/Library/Caches/Lunar/swiftybeaver.log
17:06:51.012 INFO Util.getSerialNumberHash():57 - D477EF8AAB68518670C778D50B93E2197865440342519014868C3C20481FA1D1
17:06:51.013 INFO AppDelegate.sendAnalytics():654 - Sending analytics
["data": "id=D477EF8AAB68518670C778D50B93E2197865440342519014868C3C20481FA1D1 version=3.1.5 clamshell=false displays=1 mode=manual machine=iMac14,1"]
17:47:27.902 ERROR AppDelegate.locationManager():762 - Location manager failed with error: Error Domain=kCLErrorDomain Code=0 "(null)"
18:11:21.991 INFO Display.adapt():1055 -
DELL P2416D:
	Brightness: 5
	Contrast: 20
18:16:36.093 INFO Util.getSerialNumberHash():57 - D477EF8AAB68518670C778D50B93E2197865440342519014868C3C20481FA1D1
18:16:36.098 INFO BrightnessAdapter.addSentryData():234 - Creating Sentry extra context
18:16:36.105 INFO AppDelegate.applicationDidFinishLaunching():707 - Setting log path to /Users/mathishaane/Library/Caches/Lunar/swiftybeaver.log
18:16:36.225 INFO Util.getSerialNumberHash():57 - D477EF8AAB68518670C778D50B93E2197865440342519014868C3C20481FA1D1
18:16:36.226 INFO AppDelegate.sendAnalytics():654 - Sending analytics
["data": "id=D477EF8AAB68518670C778D50B93E2197865440342519014868C3C20481FA1D1 version=3.1.5 clamshell=false displays=1 mode=manual machine=iMac14,1"]
18:16:55.552 INFO ModernWindowController.windowWillClose():29 - Window closing
18:17:28.621 INFO ModernWindowController.windowWillClose():29 - Window closing
18:17:42.357 INFO Util.getSerialNumberHash():57 - D477EF8AAB68518670C778D50B93E2197865440342519014868C3C20481FA1D1
18:17:42.362 INFO BrightnessAdapter.addSentryData():234 - Creating Sentry extra context
18:17:42.368 INFO AppDelegate.applicationDidFinishLaunching():707 - Setting log path to /Users/mathishaane/Library/Caches/Lunar/swiftybeaver.log
18:17:42.481 INFO Util.getSerialNumberHash():57 - D477EF8AAB68518670C778D50B93E2197865440342519014868C3C20481FA1D1
18:17:42.482 INFO AppDelegate.sendAnalytics():654 - Sending analytics
["data": "id=D477EF8AAB68518670C778D50B93E2197865440342519014868C3C20481FA1D1 version=3.1.5 clamshell=false displays=1 mode=manual machine=iMac14,1"]
18:17:58.322 INFO Display.adapt():1055 -
DELL P2416D:
	Brightness: 5
	Contrast: 20
18:18:01.245 INFO Display.adapt():1055 -
DELL P2416D:
	Brightness: 11
	Contrast: 20
18:18:01.578 INFO Display.adapt():1055 -
DELL P2416D:
	Brightness: 31
	Contrast: 20
18:18:03.252 INFO Display.adapt():1055 -
DELL P2416D:
	Brightness: 32
	Contrast: 20
18:18:03.286 INFO Display.adapt():1055 -
DELL P2416D:
	Brightness: 33
	Contrast: 20
18:18:03.331 INFO Display.adapt():1055 -
DELL P2416D:
	Brightness: 34
	Contrast: 20
18:18:03.883 INFO Display.adapt():1055 -
DELL P2416D:
	Brightness: 35
	Contrast: 20
18:18:04.980 INFO Display.adapt():1055 -
DELL P2416D:
	Brightness: 35
	Contrast: 29
18:18:05.148 INFO Display.adapt():1055 -
DELL P2416D:
	Brightness: 35
	Contrast: 39
18:18:07.268 INFO Display.adapt():1055 -
DELL P2416D:
	Brightness: 35
	Contrast: 53
18:18:09.395 INFO Display.adapt():1055 -
DELL P2416D:
	Brightness: 35
	Contrast: 50
18:18:18.440 INFO Display.adapt():1055 -
DELL P2416D:
	Brightness: 84
	Contrast: 70
18:18:20.600 INFO Display.adapt():1055 -
DELL P2416D:
	Brightness: 35
	Contrast: 50
18:18:23.649 INFO Display.adapt():1055 -
DELL P2416D:
	Brightness: 84
	Contrast: 70
18:18:28.946 INFO AppDelegate.applicationWillTerminate():734 - Going down
18:18:28.948 INFO ModernWindowController.windowWillClose():29 - Window closing
20:36:47.651 INFO Util.getSerialNumberHash():57 - D477EF8AAB68518670C778D50B93E2197865440342519014868C3C20481FA1D1
20:36:47.656 INFO BrightnessAdapter.addSentryData():234 - Creating Sentry extra context
20:36:47.657 INFO AppDelegate.applicationDidFinishLaunching():707 - Setting log path to /Users/mathishaane/Library/Caches/Lunar/swiftybeaver.log
20:36:47.715 WARNING BrightnessAdapter.adaptBrightness():413 - Day moments aren't fetched yet
20:36:47.716 WARNING BrightnessAdapter.adaptBrightness():413 - Day moments aren't fetched yet
20:36:47.786 WARNING BrightnessAdapter.adaptBrightness():413 - Day moments aren't fetched yet
20:36:47.793 INFO Util.getSerialNumberHash():57 - D477EF8AAB68518670C778D50B93E2197865440342519014868C3C20481FA1D1
20:36:47.794 INFO AppDelegate.sendAnalytics():654 - Sending analytics
["data": "id=D477EF8AAB68518670C778D50B93E2197865440342519014868C3C20481FA1D1 version=3.1.5 clamshell=false displays=1 mode=location machine=iMac14,1"]
20:36:53.335 INFO Display.adapt():1055 -
DELL P2416D:
	Brightness: 74
	Contrast: 70
20:36:55.079 INFO Display.adapt():1055 -
DELL P2416D:
	Brightness: 35
	Contrast: 50
20:38:17.425 INFO ModernWindowController.windowWillClose():29 - Window closing
20:50:41.029 ERROR AppDelegate.locationManager():762 - Location manager failed with error: Error Domain=kCLErrorDomain Code=0 "(null)"
```

Thanks in advance.

**Comment by alin23** [comment] 2020-04-15 07:28
@Enaah looks like Lunar detects the brightness being changed and sends it to the monitor. Does Manual or Location mode work for you on the iMac? Can Lunar actually change the brightness of your external monitor in any way?

Lunar is based on the DDC protocol which can be better tested with [ddcctl](https://github.com/kfix/ddcctl). If you can, please compile that tool and see if that can change your brightness. If it can't then it's a connection issue between your iMac and your monitor that's stopping the DDC messages from reaching your monitor. Either a bad cable, or a bad adapter.

**Comment by Enaah** [comment] 2020-04-15 11:42
Yes, _Manual_ and _Location Mode_ do work.
I also can control the Display with ddcctl:

```
╰─ ./ddcctl -d 1 -c 50                                                                      ─╯
D: NSScreen #724044116 (1440x2560 90°) 124.00 DPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: 6RC2C5340W8U
I: got edid.name: DELL P2416D
I: got edid.name: æþ
I: got edid.serial: æþ
D: action: c: 50
D: setting VCP control #18 => 50
```

On _Sync Mode_ the Display immediately goes to the lowest brightness.

**Comment by alin23** [comment] 2020-04-15 11:47
Please run the diagnostics from the Lunar menu: 
![image](https://user-images.githubusercontent.com/3819725/79333789-c98af280-7f27-11ea-82d2-d1c1b7fb4016.png)

It will try to open a new Github issue. Skip that and just let me know when the diagnostics have finished.

**Comment by alin23** [comment] 2020-04-15 11:48
And thank you so much for the coffee! ☕ 🌕

**Comment by alin23** [comment] 2020-04-15 12:43
@Enaah can you please run the diagnostics again? I had a bug in the server and the output got truncated.

**Comment by Enaah** [comment] 2020-04-15 19:45
https://github.com/alin23/Lunar/issues/97

**Comment by alin23** [comment] 2020-04-15 20:00
Thanks, can you also send me screenshots of all the three pages of the Lunar UI? 
* Display: the white page
* Configuration: the yellow page
* Hotkeys: the mauve page

**Comment by Enaah** [comment] 2020-04-15 21:21
Here you go:

> Display: the white page

![Screenshot 2020-04-15 23 20 11](https://user-images.githubusercontent.com/10073766/79390274-b6037a00-7f6f-11ea-9ca6-8c03b4cb5e9f.png)

> Configuration: the yellow page

![Screenshot 2020-04-15 23 20 13](https://user-images.githubusercontent.com/10073766/79390301-be5bb500-7f6f-11ea-94ff-00f1352fe06b.png)

> Hotkeys: the mauve page

![Screenshot 2020-04-15 23 20 19](https://user-images.githubusercontent.com/10073766/79390310-c4519600-7f6f-11ea-956e-60f020b8e9c5.png)

**Comment by alin23** [comment] 2020-04-15 21:26
Thanks! I was hoping for the screenshots with the Sync mode enabled as the UI contains different settings in that mode. But I guess you don't have any extreme values. I'll look over this tomorrow.

**Comment by Enaah** [comment] 2020-04-15 21:38
Thanks, an no pressure. It's not urgent. ✌🏼

**Comment by alin23** [comment] 2021-05-31 13:49
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*

**Closed by alin23** 2021-05-31 13:49 UTC

**Comment by Enaah** [comment] 2021-08-31 23:16
Man, you`re wild!

You are pushing a lot of updates and now it works in sync-mode with my old iMac 2013 and my new Macbook with DIsplay Link. A few month ago it was not working at all.

Great dude! 🙌🏼

**Comment by Enaah** [comment] 2021-09-02 09:09
Okay, I#Ve to correct, the Indication is syncing with **DisplayLink** but it has no effect.
I don't know if it's possible with **DisplayLink**.
✌🏼

**Comment by alin23** [comment] 2021-09-02 09:11
DisplayLink drivers don't implement DDC or Gamma controls so there's no way to control a DisplayLink monitor from the Macbook.

The only way Lunar can control DisplayLink is through a Network Controller, you can read about that here: https://lunar.fyi/#fallback
