### ISSUE TITLE
Start at login not working - Lunar Bug

### ISSUE THREAD

**Issue by sidharthv96** [alin23/Lunar#158] opened 2020-09-01 06:16 UTC
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *Macbook Pro 2019 - macOS 10.15.6 (19G2021)*

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    *N/A*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *N/A*

- Using an USB Docking Station or Hub:
    *N/A*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *N/A*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
   *N/A*

# Issue description:
Auto start at login is not working, even after the option is selected.
![image](https://user-images.githubusercontent.com/10703445/91803579-a946a080-ec48-11ea-9d89-e51d7b1592e1.png)

**Comment by alin23** [comment] 2020-09-01 06:38
Yes, this has been reported before, then it was fixed by introducing LauchAtLogin.framework. Now it seems broken again.

I'm a bit overwhelmed with the feedback and requests I get on Lunar nowadays but I'll try to make some time to fix this.

**Comment by sidharthv96** [comment] 2020-09-01 06:52
If it helps, I'm also using [yubiswitch](https://github.com/pallotron/yubiswitch) and[ Hammerspoon](https://github.com/Hammerspoon/hammerspoon), where auto open works. 

If you can give few pointers, I can try to raise a PR. But I don't have any experience with native apps, so I'm not sure if I'd be of much help.

Thanks for the amazing app btw!

**Comment by alin23** [comment] 2020-09-01 06:57
I'm using a third-party library that does all the Start at Login stuff so I'll probably just have to upgrade that. Don't worry about the PR 😊

**Comment by CaptainCustard** [comment] 2020-12-27 13:16
Any updates? :)

**Comment by alin23** [comment] 2020-12-27 15:29
This looks to have been fixed with the framework upgrade but I still have work in progress on other features so I can't release a new version right now. 

I'll do my best to release Lunar 4 in January

**Comment by alin23** [comment] 2021-05-31 13:39
Fixed in **Lunar 4**. It only took me 5 months since my last promise. oh boy.. time flies

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*

**Closed by alin23** 2021-05-31 13:39 UTC
