### ISSUE TITLE
Allow Pro Display XDR & other monitors w/ auto-brightness to be the sync source

### ISSUE THREAD

**Issue by swrobel** [alin23/Lunar#250] opened 2021-01-21 00:33 UTC
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    LG Ultrafine 22" - YES
	Apple Pro Display XDR - NO

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 16" (2020)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Thunderbolt / USB-C

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    No (note: you probably can remove the note about compiling a C program because ddcctl binaries are now available)

# Issue description
Honestly, this isn't a big deal because the Pro Display supports its own auto-brightness and the sensor seems to behave similarly to that in my Macbook. However, for users that have it as their primary display with a Macbook in clamshell mode, or a displayless Mac, it would be useful to be able to use it as the **source** device and have other external displays follow its sensor.

Lunar Diagnostics Report [F59C5AE43C7EAF863F0226DA36E26C8CCF12262AA451F7C812B238F6D56CD639] [3.2.3]

**Comment by alin23** [comment] 2021-05-31 13:34
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*

**Comment by swrobel** [comment] 2021-06-15 02:36
The situation in Lunar 4 seems worse, as I don't seem to be able to set the sync mode for each monitor individually. I attempted to work around this by setting my Pro Display to "locked" as you can see below, but every so often, it seems that Lunar tries to change the brightness and fights with the macOS auto-brightness.

<img width="939" alt="Screen Shot 2021-06-14 at 7 35 01 PM" src="https://user-images.githubusercontent.com/157270/121984339-a506f200-cd47-11eb-9d55-3720ce948fce.png">

**Comment by alin23** [comment] 2021-06-15 07:12
You can disable adaptiveness per monitor from the gear icon near the RESET button. 

Lunar 4.1.0 will be released this week and will support exactly this feature. You'll be able to select one of the Pro Display monitors as the source for others.

**Comment by alin23** [comment] 2021-06-15 21:19
Done in v4.1.0!

![Shot_Lunar_Settings_qB257g23](https://user-images.githubusercontent.com/3819725/122124867-87658580-ce38-11eb-9f64-cb963e44eabc.png)

**Closed by alin23** 2021-06-15 21:19 UTC
Labels: diagnostics
