### ISSUE TITLE
Sudden brightness change

### ISSUE THREAD

**Issue by fireteam99** [alin23/Lunar#439] opened 2022-02-19 23:55 UTC
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    MacBook Pro (16-inch, 2021)

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell U2415

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    DisplayPort-to-miniDisplayPort-to-USB-C

- Using an USB Docking Station or Hub:
    Using miniDisplayPort-to-USB-C adaptor

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Manual*

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. Follow through the steps when asked

![Lunar Diagnostics menu item](https://files.lunar.fyi/diagnostics-menu-item.png)

    Yes
<img width="1018" alt="Screen Shot 2022-02-19 at 6 33 20 PM" src="https://user-images.githubusercontent.com/17861378/154822788-92449080-b8be-41cc-969e-a8d621490224.png">

# Issue description:
Monitors controlled by lunar have a tendency to suddenly go up to max brightness randomly. The frequency of this occurring is extremely variable, sometimes happening twice an hour and other times about once a day. Adjusting the brightness using hot keys will immediately reset the brightness back to normal.

**Comment by alin23** [comment] 2022-02-20 07:15
Hi @fireteam99 !

Can you try quitting Lunar for a while and check if this never happens with Lunar quit?
Some monitors reset their brightness in their firmware, I doubt this is coming from Lunar.

Lunar doesn't do any automatic adjustments in Manual mode so there's no reason for this to happen.

The only automatic adjustment could come from App Presets, but then changing the brightness should not set it back to what it was before, so it doesn't seem likely.

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/3819725/154832539-0c971da1-e0b3-4052-a20c-84d63db5bd7b.png">

**Comment by chengzhenyee** [comment] 2022-02-20 10:34
I'm having the exact issue as well after updating to the latest version.

**Comment by alin23** [comment] 2022-02-20 10:36
@chengzhenyee would you like to hop on Lunar's Discord to try some troubleshooting? https://discord.gg/dJPHpWgAhV

**Comment by fireteam99** [comment] 2022-02-20 22:32
@alin23 I will disable lunar for a day today and see if it still happens, will report back.

**Comment by chengzhenyee** [comment] 2022-02-21 10:36
> @chengzhenyee would you like to hop on Lunar's Discord to try some troubleshooting? https://discord.gg/dJPHpWgAhV

Did a factory reset on my monitor and it appears to be okay now. I'm using MacBook Air M1 and LG 35WN75C connected via USB-C, manual mode on Lunar. 

I've joined the discord channel btw.

**Comment by alin23** [comment] 2022-02-21 10:37
@chengzhenyee what's your username?

**Comment by fireteam99** [comment] 2022-02-21 16:16
I turned lunar off, and the issue hasn't occurred for the past 8 hours. I'll look into factory reseting my monitors though and see if that works.

**Comment by fireteam99** [comment] 2022-02-21 19:23
@alin23 Thanks for specifying, I've made sure that Dynamic Contrast is off and I am on the standard preset. I haven't seen the issue occur for the past hour or so but I'll report back at the end of the day.

**Comment by fireteam99** [comment] 2022-02-22 04:58
I have not seen this issue occur for the last 12 hours or so after factory resetting my monitors. @alin23 should I close this issue for now?

**Comment by fireteam99** [comment] 2022-02-22 05:26
Update: the issue just happened again with one of my monitors suddenly shifting to full brightness.

**Comment by alin23** [comment] 2022-02-22 10:07
@fireteam99 I've left some troubleshooting steps on Discord. Let's talk there until we find the problem. We can update this issue with the result afterwards.

**Comment by mustdobetter** [comment] 2022-03-02 17:29
Just to add that I'm suddenly experiencing this with my Apple Display XDR and attached LG Ultrafine 5k with the latest 5.4.0 update today. I'm going to try reverting back to an earlier version and see if this helps. I'll report back once I've done that.

**Comment by michaelworm** [comment] 2022-03-09 09:28
I've got the same issue occuring since yesterday after updating Lunar to latest version, but only on Sensor mode (I am using the self built adafruit board sensor from the lunar website). 
In my case the brightness goes up about +20 brightness and instantly resets to the brightness before the change.
Strangely when the sun goes down, the brightness will be set lower to actual brightness but when the sun is rising in my area, it will be set higher than my current brightness. This occurs about every 10-20 seconds. 
Is this a bug in the current version? Disabling sensor mode and using location mode is not changing brightness as I described - everything is running normally.

**Comment by alin23** [comment] 2022-03-09 13:56
Hi Michael!

This is probably unrelated to this issue, and more likely related to the Gamma reset logic that I had to add because of a macOS change.

Is your monitor using Software Dimming?

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/3819725/157455648-2a97db42-98b8-4c56-9eea-ccda718fe3ce.png">

Do you want to get on Discord for a troubleshooting session?

**Comment by michaelworm** [comment] 2022-03-09 16:36
Hey @alin23 I created a new issue #442

**Comment by alin23** [comment] 2022-03-11 10:04
@fireteam99 here's a beta with another possible fix after the logs from @michaelworm indicated this could be a problem with Location Mode still working in the background: https://files.lunar.fyi/Lunar-5.4.3-beta7.zip

I'm still investigating, but if you have any logs from beta6, it would be helpful to see if the problem is the same because I've removed those logging messages from beta7.

**Comment by fireteam99** [comment] 2022-03-12 01:33
@alin23 I haven't the issue occur yet after using beta 6 for about 10 hours now, do you want me to keep on using 6 or switch to 7?

**Comment by alin23** [comment] 2022-03-12 08:04
Better keep using beta 6 in case the issue appears again and it's caused by something different. 

If you don't get the issue again, I'll release v5.4.4 with all the fixes by Monday

**Comment by fireteam99** [comment] 2022-03-13 16:17
@alin23 Here is a copy of the full logs, I wasn't able to upload it to discord because the file was too large: [lunar-full.gz](https://github.com/alin23/Lunar/files/8240124/lunar-full.gz)

**Comment by trm217** [comment] 2022-03-18 22:18
Also just noticed this issue today. Switching to 100% brightness seems to occur every 2 - 4 minutes.

**Comment by alin23** [comment] 2022-03-20 10:07
This should be fixed in v5.5.1. 

Some monitors can also have this as a firmware bug, where they reset the brightness after some number of DDC commands.

If it ever happens, please first check if Lunar's **🔴 Manual Mode** and [🖥 MonitorControl](https://monitorcontrol.app/) don't exhibit the same problem.

**Closed by alin23** 2022-03-20 10:07 UTC
