### ISSUE TITLE
Issue with audio volume increasing on laptop lid close / open

### ISSUE THREAD

**Issue by vguerci** [alin23/Lunar#94] opened 2020-04-14 12:55 UTC
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *Macbook Pro 2019*

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    *LG 27UL850-W 4k HDR*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *USB-C-to-USB-C*

- Using an USB Docking Station or Hub:
    *No*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Any*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *Yes*
# Issue description:
I'm using laptops with an external screen. Most of the time with the lid closed, but occasionally I have to open / close it. Each time I do this, the audio volume of the monitor does not change.
But when I use the volume keys after through Lunar "Use media keys as hotkeys", the audio volume of the monitor is reset to something like 80%.

Thanks a lot for your time building this great tool, loving it <3
Abusing this ticket, but would it be conceivable to plug an external light sensor? Like a DIY thingy on USB or else.

**Comment by alin23** [comment] 2020-04-14 13:17
I don't really understand the issue here. 
This is how I understand it:

##### first
1. Lid closed
2. Enabled options: _"Use media keys as hotkeys"_ and _"Change monitor volume with volume keys"_
3. Changing volume with volume keys works

##### then
1. Lid opened
2. Enabled options: _"Use media keys as hotkeys"_ and _"Change monitor volume with volume keys"_
3. Changing volume with volume keys does not work anymore?

##### then
1. Lid opened
2. Enabled options: _"Use media keys as hotkeys"_ and _"Change monitor volume with volume keys"_
3. You do something magic _(this is what I don't understand)_
3. Changing volume with volume keys works again?

The volume reset probably happens because Lunar can't read the monitor volume and just sets the last known volume value.

Thanks for asking about the external light sensor! I'm actually working on a hardware solution using an ATTiny85. I plan on open-sourcing it so that everyone can just order the parts on Amazon/eBay/AliExpress, connect them and use the module with Lunar.

I'll also try to ship some modules for people that are not technical enough to build their own, but I'm still unsure how to do that as the postal service in my country is very unreliable.

**Comment by vguerci** [comment] 2020-04-14 13:41
Hey, thanks for the quick reply.
Sorry for being unclear, but I have no issue with volume keys that always works. It is just that after a lid close or open, as soon as I use the volume key Lunar change monitor volume to 80%. As if detecting the laptop screen was changing the value known by Lunar. IMO the Lunar "Last known value" should only be associated to the external monitor one and not affected by lid close / open. Is that more clear?

Ah this is so great to read that about the external sensor. Please let me know if you want some beta testing, I am confortable with soldering, even small SMD, also have basic knowledge of Kicad. :)

**Comment by alin23** [comment] 2020-04-14 14:04
I see, so the problem is the resetting of the volume. 

The volume is not tied to lid close/open, but when you open/close the lid, the system has to recompute the screen configuration, and Lunar has to adapt to that by starting from scratch. 
That means deleting the current display objects, getting the new configuration from the system and trying to match the new displays with the stored per-display settings.

By doing that, the volume/brightness/contrast threads have to be restarted and thus the volume gets set again. 

Although I think that should only happen if you have this option enabled:
![image](https://user-images.githubusercontent.com/3819725/79233443-8bcb9280-7e71-11ea-90a4-f8b7308a0d2d.png)

But it is indeed a bug, I'll fix it in the next version.

Very nice to hear that you are experienced with hardware 😊
I hope you don't mind if I ask you some things while I go through the process of creating this module. I can do functional DYI modules but I've never done a production hardware product so I'll need help there. I really don't want to fry up people's devices

**Comment by vguerci** [comment] 2020-04-14 14:25
The read option is disabled. Thanks for looking into It, let me know if I can help, I'm confortable at swift / Xcode and such.

I'm far from an hardware expert but feel free to ask, I would love a new toy to build&play :)

**Comment by alin23** [comment] 2020-04-23 11:18
This should be fixed in 3.2.0. It was a copy-paste typo I forgot to fix. The volume was being restored from the last contrast value.

The light sensor feature will be tackled in a different issue. If you want you can create a feature request issue where we can discuss that in detail. I'm very busy with my daily job these days, but I hope to get to that soon.

**Closed by alin23** 2020-04-23 11:18 UTC

**Comment by vguerci** [comment] 2020-04-23 11:53
Thanks a lot! :)
